version: 2

general:
  branches:
    only:
      - master
      - develop

jobs:
  build:
    working_directory: ~/inventory-service

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    environment:
      JVM_OPTS: -Xmx2g

    steps:
      - checkout

      - restore_cache:
          key: inventory-service-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: inventory-service-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports